[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  directory = "netlify/functions"
  included_files = ["data/small_data.csv"]

[[redirects]]
  from = "/server"
  to = "/.netlify/functions/recommendify"
  status = 200
  force = true
